name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionid: ae8c25df-a8b2-4b8b-a5d2-2f8f4d903b36
          region: East US
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions